FROM nginx:mainline-alpine
MAINTAINER gisolfi@us.ibm.com

# RUN apk update ; \
#     apk upgrade ; \
#     apk add nano curl ; \
#     apk add --no-cache bash ; \
#     apk add python3 py-pip ; \
#     apk add gcc musl-dev jpeg-dev zlib-dev ; \
#     apk add libffi-dev cairo-dev pango-dev gdk-pixbuf-dev ; \
#     apk upgrade

RUN apk update ; \
    apk upgrade ; \
    apk add nano curl ; \
    apk add --no-cache bash

RUN apk add --no-cache python3 && \
        python3 -m ensurepip && \
        rm -r /usr/lib/python*/ensurepip && \
        pip3 install --upgrade pip setuptools && \
        if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
        if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
        rm -r /root/.cache

RUN apk add gcc musl-dev jpeg-dev zlib-dev ; \
    apk add libffi-dev cairo-dev pango-dev gdk-pixbuf-dev ; \
    apk upgrade

RUN rm -rf /etc/nginx/conf.d ; rm /usr/share/nginx/html/*

WORKDIR /usr/share/nginx

COPY . /usr/share/nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

#----------------------------------------------------
# Install MkDocs environment w/complimentary tools
#----------------------------------------------------
RUN pip install --upgrade pip
RUN pip install mkdocs==1.0.4
RUN pip install mkdocs-material
RUN pip install mkpdfs-mkdocs==1.0.1

RUN mkdocs build
