FROM ubuntu:latest
MAINTAINER gisolfi@us.ibm.com

# Install Python3 and WeasyPrint dependencies
#RUN add-apt-repository ppa:ubuntu-toolchain-r/test ; \
RUN apt-get update ; \
    apt-get install software-properties-common ; \
#    apt-get install -y apt-utils && apt-get install -y curl ; \
    add-apt-repository ppa:ubuntu-toolchain-r/test ; \
    apt-get update ; \
    sudo apt-get install -y python3-pip python3-dev ; \
      build-essential python3-setuptools ; \
      python3-wheel python3-cffi libcairo2 ; \
      libpango-1.0-0 libpangocairo-1.0-0 ; \
      libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

# Configure Python3
RUN cd /usr/local/bin ; \
    ln -s /usr/bin/python3 python ; \
    && pip3 install --upgrade pip

# Install Nginx
RUN add-apt-repository -y ppa:nginx/stable ; \
    apt-get update ; \
    apt-get install -y nginx ; \
    rm -rf /var/lib/apt/lists/* ; \
    chown -R www-data:www-data /var/lib/nginx

RUN rm -rf /etc/nginx/conf.d ; rm /usr/share/nginx/html/*

# Define working directory.
WORKDIR /etc/nginx

COPY . /usr/share/nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

#----------------------------------------------------
# Install MkDocs environment w/complimentary tools
#----------------------------------------------------
RUN pip install mkdocs==1.0.4
RUN pip install mkdocs-material
RUN pip install mkpdfs-mkdocs==1.0.1

RUN mkdocs build
